version: '2'

services:
  eureka:
    extends:
      file: api/eureka/docker-compose.yml
      service: eureka
  image-processor-requests-server:
    extends:
      file: api/imageProcessorRequestsServer/docker-compose.yml
      service: image-processor-requests-server
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure
  image-region-processor-server:
    extends:
      file: api/imageRegionProcessor/docker-compose.yml
      service: image-region-processor-server
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure
  auth:
    extends:
      file: api/auth/docker-compose.yml
      service: auth
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure
  zuul:
    extends:
      file: api/zuul/docker-compose.yml
      service: zuul
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure
  grafana:
    extends:
      file: grafana/docker-compose.yml
      service: grafana
  prometheus:
    extends:
      file: prometheus/docker-compose.yml
      service: prometheus
  management-portal:
    extends:
      file: management-portal/docker-compose.yml
      service: management-portal
  nginx:
    extends:
      file: nginx/docker-compose.yml
      service: nginx
    depends_on:
        - image-processor-requests-server
        - grafana
        - prometheus
        - management-portal
        - auth
        - zuul
        - eureka

networks:
  chemBalancerNet:
