version: '2'

services:
  auth:
    build: ../api/auth
    ports:
      - "9100:9100"
    image: "bphun/chemical-equation-balancer:auth"
    container_name: auth
    networks:
      - chemBalancerNet
    mem_limit: 500m
    memswap_limit: 500m
    mem_reservation: 450m

networks:
  chemBalancerNet: