version: '2.2'

services:
  eureka:
    build: ../api/eureka
    ports:
      - "8761:8761"
    image: "bphun/chemical-equation-balancer:eureka"
    container_name: eureka
    networks:
      - chemBalancerNet

networks:
  chemBalancerNet: