version: '2'

services:
  eureka:
    build: ../api/eureka
    ports:
      - "8761:8761"
    image: "bphun/chemical-equation-balancer:eureka"
    container_name: eureka
    networks:
      - chemBalancerNet
    mem_limit: 500m
    memswap_limit: 500m
    mem_reservation: 450m

networks:
  chemBalancerNet: