version: '2.2'

services:
  image-processor-requests-server:
    build: ../api/imageProcessorRequestsServer
    ports:
      - "8080:8080"
    image: "bphun/chemical-equation-balancer:image-processor-requests-server"
    container_name: image-processor-requests-server
    networks:
      - chemBalancerNet

networks:
  chemBalancerNet: