version: '2'

services:
  management-portal:
    build: ../management-portal
    ports:
      - "5000:5000"
    image: "bphun/chemical-equation-balancer:management-portal"
    container_name: management-portal
    networks:
      - chemBalancerNet
    mem_limit: 25m
    memswap_limit: 25m

networks:
  chemBalancerNet:
