version: '2'

services:
  nginx:
    build: ../nginx
    ports:
      - "80:7080"
      - "443:7443"
    image: "bphun/chemical-equation-balancer:nginx"
    container_name: nginx
    networks:
      - chemBalancerNet
    mem_limit: 10m
    memswap_limit: 10m

networks:
  chemBalancerNet:
