version: '2.2'

services:
  prometheus:
    build: ../monitoring/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheusData:/prometheus
    image: "bphun/chemical-equation-balancer:prometheus"
    container_name: prometheus
    networks:
        - chemBalancerNet
    
networks:
  chemBalancerNet:
