version: '2'

services:
  image-region-processor-server:
    build: ../api/imageRegionProcessor
    ports:
      - "8081:8081"
    image: "bphun/chemical-equation-balancer:image-region-processor-server"
    container_name: image-region-processor-server
    networks:
      - chemBalancerNet
    mem_limit: 500m
    memswap_limit: 500m
    mem_reservation: 450m

networks:
  chemBalancerNet: