version: '2.2'

services:
  zuul:
    build: ../api/zuul
    ports:
      - "7080:7080"
    image: "bphun/chemical-equation-balancer:zuul"
    container_name: zuul
    networks:
      - chemBalancerNet

networks:
  chemBalancerNet: