version: '2'

services:
  auth:
    build: .
    ports:
      - "9100:9100"
    image: "bphun/chemical-equation-balancer:auth"
    container_name: auth
    networks:
      - chemBalancerNet
    mem_limit: 200m
    memswap_limit: 200m
    mem_reservation: 160m

networks:
  chemBalancerNet: