version: '2'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    image: "bphun/chemical-equation-balancer:nginx"
    container_name: nginx
    networks:
      - chemBalancerNet

networks:
  chemBalancerNet:
