version: '2'

services:
  zuul:
    build: .
    ports:
      - "7080:7080"
    image: "bphun/chemical-equation-balancer:zuul"
    container_name: zuul
    networks:
      - chemBalancerNet
    mem_limit: 200m
    memswap_limit: 200m
    mem_reservation: 160m

networks:
  chemBalancerNet: