version: '2'

services:
  api-server:
    build: .
    ports:
      - "8080:8080"
    image: "bphun/chemical-equation-balancer:api"
    container_name: api-server
    networks:
      - chemBalancerNet

networks:
  chemBalancerNet: