spring:
    datasource:
        url: jdbc:mysql://chemicalequationbalancerdatabase.cz5vjghh05gt.us-west-1.rds.amazonaws.com:3306/ChemicalEquationBalancerDatabase
        username: admin
        password: Bphun62391!
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    application:
        name: image-processor-request-server

amazonProperties:
    endpointUrl: https://s3.us-west-1.amazonaws.com
    accessKey: AKIARGRUKLUVX2P2O3N7
    secretKey: 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
    bucketName: chemical-equation-balancer-image-bucket
    sqsUrl: https://sqs.us-west-1.amazonaws.com/082787851563/regionExtractionQueue
crossOrigin:
    frontendHostname: '*'

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,auditevents,caches,conditions,httptrace,metrics,scheduledtasks,heapdump

server:
    tomcat:
        mbeanregistry:
            enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka
          
