spring:
    datasource:
        url: jdbc:mysql://chemicalequationbalancerdatabase.cz5vjghh05gt.us-west-1.rds.amazonaws.com:3306/ChemicalEquationBalancerDatabase
        username: admin
        password: Bphun62391!
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    application:
        name: image-processor-request-server

amazonProperties:
    endpointUrl: https://s3.us-west-1.amazonaws.com
    accessKey: AKIARGRUKLUV4B774UWU
    secretKey: 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
    bucketName: chemical-equation-balancer-image-bucket
    sqsUrl: https://sqs.us-west-1.amazonaws.com/082787851563/regionExtractionQueue
crossOrigin:
    frontendHostname: '*'

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,auditevents,caches,conditions,httptrace,metrics,scheduledtasks,heapdump

server:
    tomcat:
        mbeanregistry:
            enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka
            
# The format used for the keystore
# server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
# server.ssl.key-store=chemEquBalancerApi.p12
# The password used to generate the certificate
# server.ssl.key-store-password=62391bphun
# The alias mapped to the certificate
# server.ssl.key-alias=chemEquBalancerApi

# logging.level.org.springframework=debug
# logging.level.org.hibernate=debug
